### ISSUE TITLE
Sleep during sensor reading methods

### ISSUE THREAD

**Issue by joshmcculloch** [adafruit/Adafruit_CircuitPython_ICM20X#15]
Hi, I'm looking for justification for the sleep functions in the sensor reading methods.
There is a commit from May 2020 stating they were added to fix timing issues. But I wonder if they really needed to be added to the sensor reading methods. They significantly reduce the max sample rate on the raspberry pi, and I haven't had any issues since removing them:
https://github.com/adafruit/Adafruit_CircuitPython_ICM20X/commit/516f2dc71a0ad1a714907d5b4332997b9cf7c6ec
I'd like to create a pull request unless I have mistaken their purpose.

**Comment by ladyada** [comment]
you could do a PR, and we may test/merge when we can!

**Comment by jposada202020** [comment]
Hello, according to my tests, there could be 3 situations that timing is important:
1. After, Reset (soft-reset) `DEVICE_RESET` in the `PWR_MGMT_1` register
2. After Sleep
3. After reading a different memory bank.  But, not sure about this.

Maybe the logic behind removing the sleep from the acc, gyro readings was that probable you could read the 6 values (7 with temp) in one shot, so time was less sensitive there.

Disclaimer: I have not tested the ICM20649.
